apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-mongodb-api
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      component: mongodb
      user: sk-chen
  template:
    metadata:
      labels:
        component: mongodb
        user: sk-chen
    spec:
      containers:
        - name: mongodb
          image: tecd010203/mongodb:api
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 20m
              memory: 64Mi
              ephemeral-storage: 64Mi
            requests:
              cpu: 20m
              memory: 64Mi
          env:
            - name: ENSAAS_SERVICES
              valueFrom:
                secretKeyRef:
                  name: mongodb-api-level1-secret
                  key: ENSAAS_SERVICES
